### ISSUE TITLE
Syntax Errors in Node v0.10.x

### ISSUE THREAD

**Issue by marybeshaw** [HustleInc/regiment#3]
We would like to use Regiment in Node v0.10.x, but it crashes node on startup due to syntax errors... I think it is because Node v0.10 doesn't support ECMAScript 2015.  If it won't work in Node v0.10 or v0.12, I'd like to suggest that you update the readme to reflect that.

**Comment by TylerBrock** [comment]
Yep, that is correct. It shouldn't even install, I specified `{ engines: { node >= 4.0.0 } }` in package.json for that reason but I will add a note to the README as well, thanks!
